from softgym.envs.pour_water import PourWaterPosControlEnv
from softgym.envs.pass_water import PassWater1DEnv
from softgym.envs.rope_flatten import RopeFlattenEnv
from softgym.envs.cloth_flatten import ClothFlattenEnv
from softgym.envs.cloth_fold import ClothFoldEnv
from softgym.envs.cloth_drop import ClothDropEnv
from collections import OrderedDict

env_arg_dict = {
    'PourWater': {'observation_mode': 'cam_rgb',
                  'action_mode': 'direct',
                  'render_mode': 'fluid',
                  'deterministic': False,
                  'render': True,
                  'headless': True,
                  'num_variations': 200,
                  'horizon': 100,
                  'camera_name': 'default_camera'},
    'RopeFlatten': {'observation_mode': 'cam_rgb',
                    'action_mode': 'picker',
                    'num_picker': 2,
                    'render': True,
                    'headless': True,
                    'horizon': 75,
                    'action_repeat': 8,
                    'render_mode': 'cloth',
                    'num_variations': 200,
                    'use_cached_states': True,
                    'deterministic': False},
    'ClothFlatten': {'observation_mode': 'cam_rgb',
                     'action_mode': 'picker',
                     'num_picker': 2,
                     'render': True,
                     'headless': True,
                     'horizon': 150,
                     'action_repeat': 8,
                     'render_mode': 'cloth',
                     'num_variations': 200,
                     'use_cached_states': True,
                     'deterministic': False},
    'ClothFold': {'observation_mode': 'cam_rgb',
                  'action_mode': 'picker',
                  'num_picker': 2,
                  'render': True,
                  'headless': True,
                  'horizon': 150,
                  'action_repeat': 8,
                  'render_mode': 'cloth',
                  'num_variations': 200,
                  'use_cached_states': True,
                  'deterministic': False},
    'ClothDrop': dict(observation_mode='cam_rgb',
                      action_mode='picker',
                      num_picker=2,
                      render=True,
                      headless=True,
                      horizon=15,
                      action_repeat=32,
                      render_mode='cloth',
                      num_variations=200,
                      use_cached_states=True,
                      deterministic=False),
    'PassWater': dict(observation_mode='cam_rgb',
                      action_mode='direct',
                      render=True,
                      headless=True,
                      horizon=75,
                      action_repeat=8,
                      render_mode='fluid',
                      delta_reward=False,
                      deterministic=False,
                      num_variations=200)
}

SOFTGYM_ENVS = OrderedDict({'ClothDrop': ClothDropEnv,
                            'PourWater': PourWaterPosControlEnv,
                            'PassWater': PassWater1DEnv,
                            'ClothFlatten': ClothFlattenEnv,
                            'ClothFold': ClothFoldEnv,
                            'RopeFlatten': RopeFlattenEnv})
