ClothPos:
  x: -1.6
  y: 2.0
  z: -0.8
ClothSize:
  x: 64
  y: 32
ClothStiff:
  stretch: 0.9
  bend: 1.0
  shear: 0.9
RenderMode: 0
Camera:
  xPos: -0.2
  yPos: 3.0
  zPos: 4.5
  xAngle: 0
  yAngle: -0.5235
  zAngle: 0